### ISSUE TITLE
Add `pre-commit` support for CI use

### ISSUE THREAD

**Issue by alnoki** [movebit/movefmt#39]
- [x] Enable a global config to apply to all projects
- [x] Enable escaping certain directories

Something like:

```yaml
-
  hooks:
  -
    args:
    - '--config'
    - 'cfg/movefmt-cofig.yaml'
  repo: 'https://github.com/movebit/movefmt'
  rev: 'movefmt-v1.0.5(beta version)'
```
